# +-----------------------------------------------------------------------+
# |                    Bump My Version Configuration
# +-----------------------------------------------------------------------+
# Reference: https://callowayproject.github.io/bump-my-version/
# +-----------------------------------------------------------------------+
#
# To release a new version:
#
#   > uv run bump-my-version bump (major|minor|patch) --commit --tag -v
#   > git push -v --follow-tags
#
# We use https://semver.org/
#
# Or set an exact version manually:
#
#   > uv run bump-my-version bump --new-version 1.5.0 --commit --tag -v
#
# Dry run (see changes without committing):
#   > uv run bump-my-version bump patch --dry-run -vv --allow-dirty
#
# +-----------------------------------------------------------------------+

[tool.bumpversion]
current_version = "0.5.0"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "django_asgi_lifespan/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""
