# pre-commit install --install-hooks --overwrite
# pre-commit autoupdate
# pre-commit run --all-files

exclude: '^docs/'
default_stages: [ commit ]

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
        args: [ "-with", "dev,tests" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '^version.txt$'
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
      - id: ruff-format

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
