# pre-commit install --install-hooks --overwrite
# pre-commit autoupdate
# pre-commit run --all-files

exclude: '^docs/'
default_stages: [ commit ]

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
        args: [ "-with", "dev,tests" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black --config ./pyproject.toml
        language: system
        types: [ python ]
        files: ^(django_asgi_lifespan|tests)/

      - id: isort
        name: isort
        entry: poetry run isort --profile black
        language: system
        types: [ python ]
        files: ^(django_asgi_lifespan|tests)/

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
