site_name: Django ASGI Lifespan
site_url: https://illagrenan.github.io/django-asgi-lifespan
repo_url: https://github.com/illagrenan/django-asgi-lifespan
repo_name: illagrenan/django-asgi-lifespan
strict: true
watch:
  - example
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - django_asgi_lifespan
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Limitations: limitations.md
  - Development: development.md
  - Reference: reference.md
  - Contributing: contributing.md
  - Credits: credits.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      baselevel: 2
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
