site_name: Django ASGI Lifespan
site_url: https://illagrenan.github.io/django-asgi-lifespan
repo_url: https://github.com/illagrenan/django-asgi-lifespan
repo_name: illagrenan/django-asgi-lifespan
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - django_asgi_lifespan
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/illagrenan/django-asgi-lifespan
      name: Github
    - icon: material/email
      link: "mailto:vaclav.dohnal@gmail.com"
