site_name: Django ASGI Lifespan
site_url: https://illagrenan.github.io/django-asgi-lifespan
repo_url: https://github.com/illagrenan/django-asgi-lifespan
repo_name: illagrenan/django-asgi-lifespan
strict: true
watch:
  - example
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - django_asgi_lifespan
nav:
  - index.md
  - installation.md
  - How to use:
      - State manager (preferred): how_to_use/context_manager.md
      - Lifespan signals (legacy): how_to_use/signals.md
      - ASGI servers compatibility: asgi.md
  - Development:
      - development.md
      - Contributing: contributing.md
  - Changelog: changelog.md
  - Credits: credits.md
  - Reference: reference.md
theme:
  name: material
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - content.code.copy
    - content.code.select
markdown_extensions:
  - tables
  - footnotes
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      baselevel: 2
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - include-markdown
  - glightbox
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
