# https://taskfile.dev

version: '3'

env:
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1

vars:
  SOURCES: django_asgi_lifespan

tasks:
  test:
    desc: Run pytests
    cmds:
      - pytest
    silent: false

  coverage:
    desc: Run coverage
    cmds:
      - pytest --cov={{.SOURCES}} --cov-branch --cov-report=xml --cov-report=term-missing tests
    silent: false

  clean:
    desc: Clean build files
    cmds:
      - >
        {{if eq OS "windows"}}
        powershell -Command Remove-Item *.egg-info, dist, .tox, coverage.xml, .coverage, .mypy_cache, .pytest_cache -Recurse -Force -ErrorAction SilentlyContinue
        {{else}}
        rm -rf *egg-info dist .tox coverage.xml .coverage .mypy_cache .pytest_cache
        {{end}}
    silent: false

  mypy:
    desc: Check setup
    cmds:
      - mypy {{.SOURCES}} tests
    silent: false

  flake8:
    desc: Check setup
    cmds:
      - flake8 {{.SOURCES}} tests
    silent: false

  lint:
    desc: Check setup
    cmds:
      - task: mypy
      - task: flake8
    silent: false

  isort:
    desc: Check setup
    cmds:
      - isort {{.SOURCES}} tests
    silent: false

  black:
    desc: Check setup
    cmds:
      - black {{.SOURCES}} tests
    silent: false

  format:
    desc: Check setup
    cmds:
      - task: isort
      - task: black
    silent: false

  doc:
    desc: Check distribution
    cmds:
      - mkdocs build
    silent: false

  bump:
    desc: Check setup
    cmds:
      - bump2version {{.CLI_ARGS}}
    silent: false

  build:
    desc: Build the package
    cmds:
      - poetry build
    silent: false

  check:
    desc: Check distribution
    cmds:
      - twine check dist/*
    silent: false

  test_install:
    desc: Try to install local dist
    vars:
      PROJECT_NAME: django-asgi-lifespan
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    deps: [ build ]
    cmds:
      - pip uninstall {{.PROJECT_NAME}} --yes
      - pip install --no-cache-dir --no-index --find-links=file:./dist {{.PROJECT_NAME}}
      - pip uninstall {{.PROJECT_NAME}} --yes
    silent: false



