name: "Development"

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        python-versions: [ "3.10", "3.11" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install Poetry
        run: |
          python -m pip install --no-input --upgrade pip
          pip install --no-input poetry

      - name: Check pyproject.toml
        run: |
          poetry check -vv -n

      - name: Install dependencies
        run: |
          poetry install -vv -n

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linters
        run: |
          poetry run task lint

      - name: Run unittests
        run: |
          poetry run task coverage

      - name: Build wheels and source tarball
        run: >-
          poetry build -vv -n

      - name: Check project build
        run: |
          poetry run task build_check

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: coverage.xml
