name: "Development"

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        python-versions: [ "3.10", "3.11", "3.12", "3.13" ]
        django-versions: [ "4.2.*", "5.0.*", "5.1.*", "5.2.*"]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
          - python-versions: "3.13"
            django-versions: "4.2.*"
          - python-versions: "3.13"
            django-versions: "5.0.*"
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Install Django
        run: |
          uv pip install --upgrade django==${{ matrix.django-versions }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linters
        run: |
          uv run task lint

      - name: Run unittests
        run: |
          uv run task coverage

      - name: Build wheels and source tarball
        run: |
          uv build

      - name: Check project build
        run: |
          uv run task build_check

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
