name: "Preview"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish_dev_build:
    name: Preview the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ "3.13" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linters
        run: |
          uv run task lint

      - name: Run unittests
        run: |
          uv run task coverage

      - name: Build wheels and source tarball
        run: |
          # Create dev version using sed to modify pyproject.toml
          sed -i 's/version = "\([^"]*\)"/version = "\1-dev.'$GITHUB_RUN_NUMBER'"/' pyproject.toml
          uv build

      - name: publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN}}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Build documentation
        run: |
          uv run mkdocs build

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
