name: "Release"

# Controls when the action will run.
on:
  # Publish package on main branch if it's tagged with 'v*'
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ "3.10" ]

    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: "Release the package"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 1000

      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --no-input --upgrade pip
          pip install poetry
          poetry install -vv -n

      - name: Build wheels and source tarball
        run: >-
          poetry build -vv -n

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: dist/*.whl
          draft: false
          prerelease: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
